### ISSUE TITLE
JsReportMVCService is no longer static and neither does the method  RenderAsync so code does not compile

### ISSUE THREAD

**Issue by frliran** [jsreport/docs#19]
var report = await JsReportMVCService.RenderAsync(new RenderRequest()

Error	There is no argument given that corresponds to the required formal parameter 'rs' of 'JsReportMVCService.JsReportMVCService(IRenderService)'

**Comment by pofider** [comment]
You can get that instance like this
```csharp
public IJsReportMVCService JsReportMVCService { get; }

public HomeController(IJsReportMVCService jsReportMVCService)
{
	JsReportMVCService = jsReportMVCService;
}
```

**Comment by frliran** [comment]
I tried your code, but it gives this error:

`An unhandled exception occurred while processing the request.
JsReportBinaryException: Error rendering report: rendering has finished with errors:Error: An error occurred while trying to execute the command: at onCriticalError ([eval]:29603:25) at tryCatcher ([eval]:36038:23) at Promise._settlePromiseFromHandler ([eval]:34061:31) at Promise._settlePromise ([eval]:34118:18) at Promise._settlePromise0 ([eval]:34163:10) at Promise._settlePromises ([eval]:34238:18) at Async._drainQueue ([eval]:31008:16) at Async._drainQueues ([eval]:31018:10) at Immediate.Async.drainQueues [as _onImmediate] ([eval]:30892:14) at processImmediate [as _immediateCallback] (timers.js:396:17) {"originalError":{"remoteStack":"Error: Recipe must be specified\n at jsreportRuntime.js:138909:13\n at tryCatcher (jsreportRuntime.js:47277:23)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45299:31)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at PromiseArray._resolve (jsreportRuntime.js:45690:19)\n at PromiseArray._promiseFulfilled (jsreportRuntime.js:45708:14)\n at Promise._settlePromise (jsreportRuntime.js:45361:26)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._settlePromise (jsreportRuntime.js:45369:21)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45241:14)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at jsreportRuntime.js:44716:21\n at nextTickCallbackWith0Args (node.js:442:9)\n at process._tickCallback (node.js:371:13)"}}(Original) Error: Error during rendering report: Recipe must be specified at [eval]:36644:23 at ConcatStream.<anonymous> ([eval]:42366:43) at emitNone (events.js:72:20) at ConcatStream.emit (events.js:166:7) at finishMaybe ([eval]:4229:14) at afterWrite ([eval]:4115:3) at nextTickCallbackWithManyArgs (node.js:486:18) at process._tickCallback (node.js:384:17) {"remoteStack":"Error: Recipe must be specified\n at jsreportRuntime.js:138909:13\n at tryCatcher (jsreportRuntime.js:47277:23)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45299:31)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at PromiseArray._resolve (jsreportRuntime.js:45690:19)\n at PromiseArray._promiseFulfilled (jsreportRuntime.js:45708:14)\n at Promise._settlePromise (jsreportRuntime.js:45361:26)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._settlePromise (jsreportRuntime.js:45369:21)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45241:14)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at Promise._resolveCallback (jsreportRuntime.js:45219:57)\n at Promise._settlePromiseFromHandler (jsreportRuntime.js:45311:17)\n at Promise._settlePromise (jsreportRuntime.js:45356:18)\n at Promise._settlePromise0 (jsreportRuntime.js:45401:10)\n at Promise._settlePromises (jsreportRuntime.js:45480:18)\n at Promise._fulfill (jsreportRuntime.js:45425:18)\n at jsreportRuntime.js:44716:21\n at nextTickCallbackWith0Args (node.js:442:9)\n at process._tickCallback (node.js:371:13)"}`

Also, which related Nugets do I need to use?
**jsreport.Binary**  OR   **jsreport.Binary.Ph2** ?

Do I still need to use 
**jsreport.Binary.Linux**   OR **jsreport.Binary.Linux.Ph2** when running on Ubuntu or other Linux servers?

Here is how I used it till now:
`var reportingService = new LocalReporting()
						.UseBinary(RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ?
									jsreport.Binary.Ph2.JsReportBinary.GetBinary() :
									jsreport.Binary.Linux.Ph2.JsReportBinary.GetBinary())
						.AsUtility()
						.Create();`

**Comment by pofider** [comment]
It seems you didn't set the Template.Recipe.

```csharp
var report = await JsReportMVCService.RenderAsync(new RenderRequest()
{
	Template = new Template
	{
		Content = "<h1>Hello world</h1>",
		Engine = Engine.None,
		Recipe = Recipe.PhantomPdf
	}
});
```

> Also, which related Nugets do I need to use?
> jsreport.Binary OR jsreport.Binary.Ph2 ?

It is up to you. The second has newer version of phantomjs which is used for convert html to pdf. The newer version has better support for more modern js/css, but it is less stable. 

> Do I still need to use
> jsreport.Binary.Linux OR jsreport.Binary.Linux.Ph2 when running on Ubuntu or other Linux servers?

You have the code right. You need to use Linux binary on Ubuntu or other linux servers.

**Comment by frliran** [comment]
I did set the Template.Recipe, like so:

```
var report = await reportingService.RenderAsync(new RenderRequest
            {
                Template = new Template
                {
                    Recipe = Recipe.PhantomPdf,
                    Engine = Engine.None,
                    Content = pdf.Content,
                    Name = pdf.FileName,
                    Phantom = new Phantom
                    {
                        Orientation = PhantomOrientation.Portrait,
                        Format = PhantomFormat.A4,
                        Header = pdf.Header,
                        HeaderHeight = "8cm",
                        Footer = pdf.Footer,
                        FooterHeight = "1cm",
                        Margin = "0mm"
                    }
                }
            });
```

**Comment by pofider** [comment]
Hm this works for me. Can you try to put just some simple strings to Content, Header, Footer?

Can you try to remove this? `Name = pdf.FileName` 
I don't think you want to use a stored template. 

Is this on windows? Do you have the latest jsreport nugets?
