### ISSUE TITLE
Wrong Recipe in Documentation?

### ISSUE THREAD

**Issue by fabich** [jsreport/docs#21]
I guess this is an error in the documentation?
https://github.com/jsreport/docs/blob/master/docs/dotnet-aspnetcore.md#modify-response

Or is there actually a Recipe.ChromePdf for jsreport.AspNetCore?

**Comment by pofider** [comment]
Yes that was by mistake.
Fixed now.

The Recipe.ChromePdf will be in v2 (which is currently in pre-release beta)

**Comment by pofider** [comment]
Thank you for reporting it...
