### ISSUE TITLE
chrome-pdf documentation for landscape

### ISSUE THREAD

**Issue by wibobm** [jsreport/docs#24]
The documentation stating 
<script>
	...
	window.JSREPORT_CHROME_PDF_OPTIONS = {
		landscape:  true
	}
</script>

will provide landscape for recipe chrome-pdf has no effect on a report.

**Comment by bjrmatos** [comment]
hi! i tried what the docs says and it works on [playground](https://playground.jsreport.net/w/bjrmatos/ylJT3n9N)

<img width="1489" alt="Captura de pantalla 2019-06-17 a las 6 23 06 p m" src="https://user-images.githubusercontent.com/4262050/59643091-139b2000-912d-11e9-9919-dae8260ccc8a.png">


what is not working for you?
