### ISSUE TITLE
JsReport date cells

### ISSUE THREAD

**Issue by leinaD-natipaC** [jsreport/docs#27]
Hello. I really like your html-to-xlsx recipe, it's been super useful. I have a problem with date cells, however.

I can only get date cells to show as 'general'. You state in your documentation that `To reach this you need to edit data-cell-format-str to match your locale.`, but it does not mention how to do that. ¿How do I set the locale of a date cell? I'm trying to set it to ES. Thank you.

**Comment by pofider** [comment]
It is taken from Os settings, but you should be also able to get it from excel
Right-click on a cell and select format. Then click the date and you should see the default.
![image](https://user-images.githubusercontent.com/2041960/73858309-7cf4ae00-4838-11ea-80d0-badca121c3de.png)

For me it works like this
```
<td data-cell-type="date" data-cell-format-str="M/d/YYYY">2019-01-22</td>
```
