### ISSUE TITLE
is this repo in sync with http://jsreport.net/learn?

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/docs#5]
i have found and issue in [jsreport docs](http://jsreport.net/learn/adapting-jsreport) and want to edit it, but seems like the repo is not in sync with the website.

specifically this [file](https://github.com/jsreport/docs/blob/master/docs/adapting-jsreport.md) has other content different than the web page.

![image](https://cloud.githubusercontent.com/assets/4262050/11884826/a3c1eb1a-a4ea-11e5-9e5c-57c9a9836a7e.png)

**Comment by pofider** [comment]
It should be. Unfortunately I forgot to push the change here.

Would be better to auto load docs in the website. I will look at it later (https://github.com/jsreport/website/issues/2)

Now is everything in sync. I also fixed the the first bug in the docs you were pointing at. Don't know what is wrong in the second case?

**Comment by bjrmatos** [comment]
> Now is everything in sync. I also fixed the the first bug in the docs you were pointing at. Don't know what is wrong in the second case?

nothing, just pointing that it was not in sync :smile:

**Comment by bjrmatos** [comment]
> It should be. Unfortunately I forgot to push the change here.
> 
> Would be better to auto load docs in the website. I will look at it later (jsreport/website#2)

thnks for the clarification!
